### ISSUE TITLE
Investigate: Limit to how many dice can be rolled

### ISSUE THREAD

**Issue by thomasloesch** [thomasloesch/diceDiscordBot#6]
Somewhere in the range of (250, 300) dice being rolled at once causes the bot to produce no output. Investigate why this is happening.

**Comment by thomasloesch** [comment]
Seems to be related to both numbers in the input.

**Comment by thomasloesch** [comment]
Seems like there is an exception being returned from the discord API. Responses to requests must be 2000 or fewer in length.

> sx.blah.discord.util.DiscordException: Error on request to https://discordapp.com/api/channels/339253103301754890/messages. Received response code 400. With response text: {"content": ["Must be 2000 or fewer in length."]}
	at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:328)
	at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:262)
	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:251)
	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:205)
	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:149)
	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:636)
	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:617)
	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:607)
	at rollBot.RollCommand.accept(RollCommand.java:32)
	at rollBot.RollCommand.accept(RollCommand.java:11)
	at com.darichey.discord.CommandRegistry.call(CommandRegistry.java:60)
	at com.darichey.discord.CommandRegistry.lambda$call$0(CommandRegistry.java:42)
	at com.darichey.discord.CommandRegistry$$Lambda$78/66238499.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.darichey.discord.CommandRegistry.call(CommandRegistry.java:42)
	at com.darichey.discord.CommandListener.handle(CommandListener.java:33)
	at com.darichey.discord.CommandListener.handle(CommandListener.java:9)
	at sx.blah.discord.api.events.EventDispatcher$ListenerEventHandler.handle(EventDispatcher.java:769)
	at sx.blah.discord.api.events.EventDispatcher.lambda$null$19(EventDispatcher.java:653)
	at sx.blah.discord.api.events.EventDispatcher$$Lambda$40/1139859215.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Not entirely sure if there is a good fix for this. Maybe add a check and show a simpler output for responses above 2000 in length? Show just the total?

Anyways, when this exception occurred there was no output from the bot. Adding a simple try/catch should fix this.

**Comment by thomasloesch** [comment]
Fixed
